### ISSUE TITLE
White bottom of main page

### ISSUE THREAD

**Issue by ethArek** [ethArek/opqpic#2]
White bottom of main page with Dark Mode enabled.

![issue](https://user-images.githubusercontent.com/45028743/77928624-f2b14f00-72a8-11ea-833e-d985277e1281.png)

**Comment by roberts98** [comment]
Seems like the main area's height is calculated wrong in CSS. I will fix this soon.

**Comment by ethArek** [comment]
Unfortunately it still doesn't work @roberts98 
Also check the mobile resolution
